POST http://localhost:3333/courses
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzMmUyNzU1OC0xNjA5LTQzOTAtODc5NC02MTgwMjc3YjBjMmUiLCJyb2xlIjoic3R1ZGVudCIsImlhdCI6MTc1NzEwNzA5NH0.-qmNU9fMXXPFeJOb-ipkPxKNH3vp59oGMPT0z-CuSx4

{
  "title": "Curso de Cobol"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/385d2939-4154-475d-9141-586a0838096a
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjY4NzkwMi1kNDkzLTQ1ODItOTU3NS1kZTViYTkwMTc3YzYiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc1NzAyODg2OX0.AKd_zOtOXnyBmPFvOT-Pll3vHYbDzGVmgnPiRiDfXa

# Para enviar arquivos via json precisa converter o arquivo de binario para hexadecimal
# Porem, isso eh mto pesado por conta disso a melhor maneira seria via multipart/form-data
# Content-Type: 

###

POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "Yago_Costa27@bol.com.br",
  "password": "123456"
}

